# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# CheckData.py
# Created on: 2015-08-25 09:03:39.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


mxd = arcpy.mapping.MapDocument("CURRENT")
layers = arcpy.mapping.ListLayers(mxd)
for layer in layers:
    desc = arcpy.Describe(layer)
    if desc.fidSet:
        print layer.name, "has {0} features selected:".format(len(desc.fidSet.split(';')))
        for row in arcpy.da.SearchCursor(layer, "*"):
            print row
